### POST a new transaction

< {%
    client.global.headers.set('Cookie', `authjs.session-token=9e2b9765-1746-4457-b18d-32c16d53280d`)
%}

POST http://localhost:8000/transactions

{
    "name": "Grocery",
    "date": "2025-06-06",
    "amount": "46.92",
    "isCredit": false,
    "account": "Amex Gold"
}

> {%
    const location = response.headers.valueOf('Location')
    client.global.set('location', location);
%}

### DELETE previous transaction
DELETE http://localhost:8000/{{location}}

### GET all transactions
GET http://localhost:8000/transactions
